#!/usr/bin/env python

#
# Run the test, check it completed successfully
#

from __future__ import print_function
try:
  from builtins import str
except:
  pass
from boututils.run_wrapper import shell, launch, getmpirun
from boutdata.collect import collect
from sys import stdout, exit

MPIRUN=getmpirun()

print("Making ZFFT test")
shell("make > make.log")

flags = [""]

code = 0 # Return code
for nproc in [1,2,4]:
    cmd = "./test_zfft"

    print("   %d processors...." % (nproc))
    r = 0
    for f in flags:
        stdout.write("\tflags '"+f+"' ... ")

        shell("rm data/BOUT.dmp.* 2> err.log")

        # Run the case
        s, out = launch(cmd+" "+f, runcmd=MPIRUN, nproc=nproc, pipe=True)
        f = open("run.log."+str(nproc)+"."+str(r), "w")
        f.write(out)
        f.close()
        r = r + 1

        # Find out if it worked
        allpassed = collect("allpassed", path="data", info=False)
        if allpassed:
            print("PASSED")
        else:
            print("FAILED")
            code = 1

if code == 0:
    print(" => All ZFFT tests passed")
else:
    print(" => Some failed tests")

exit(code)
